name: CMake

on:
  push:

permissions:
 contents: read
 actions: write

jobs:

 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install GNOME Shell and Extensions
        run: |
          sudo apt-get update
          sudo apt-get install -y gnome-shell gnome-shell-extensions
      - name: Run install.sh
        run: ./install.sh
        shell: bash
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: moveclockkuvaus.org.shell.extension.zip
          path: moveclockkuvaus.org.shell.extension.zip
