
name: Make Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  actions: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install GNOME Shell and Extensions
        run: |
          sudo apt-get update
          sudo apt-get install -y gnome-shell gnome-shell-extensions
      - name: Run install.sh
        run: ./install.sh
        shell: bash
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: moveclock@kuvaus.org.shell-extension.zip
          path: moveclock@kuvaus.org.shell-extension.zip


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: moveclock@kuvaus.org.shell-extension.zip    
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./moveclock@kuvaus.org.shell-extension.zip
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

  releasenotes:
    needs: release
    runs-on: ubuntu-latest
    name: Generate release notes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate release notes
        uses: kuvaus/changelog-releasenotes-action@v2
        with:
          changelog_format: 'auto-changelog'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


